version: '3.9'
services:
  serve:
    profiles: ["serve"]
    container_name: keeb.dev
    restart: always
    image: keeb/keeb.dev:serve
    volumes:
      - ./overlay/writing:/hexo/keeb.dev/source/_posts
    ports:
      - 4000:4000
    
  


    