version: '3.9'
services:
  serve:
    profiles: ["serve"]
    container_name: keeb.dev
    restart: always
    image: keeb/keeb.dev
    volumes:
      - ./app/web/overlay/writing:/app/source/_posts
    ports:
      - 4000:4000
    
  


    