name: Docker Image CI

on:
  create:
    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build image
      run: docker build . --file Dockerfile --tag keeb/keeb.dev:$(date +%s)
